<?php
/**
 * Abilities API registration
 *
 * @package Lean_SEO
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Lean_SEO_Abilities {

    /**
     * Register abilities.
     */
    public static function register() {
        wp_register_ability(
            'lean-seo/get-sitemap-urls',
            array(
                'label'               => __( 'Get Sitemap URLs', 'lean-seo' ),
                'description'         => __( 'Returns a list of sitemap URLs generated by Lean SEO.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_sitemap_urls' ),
                'permission_callback' => array( __CLASS__, 'can_view_sitemaps' ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'properties' => array(),
                ),
                'output_schema'       => array(
                    'type'  => 'array',
                    'items' => array(
                        'type' => 'string',
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/get-post-seo',
            array(
                'label'               => __( 'Get Post SEO', 'lean-seo' ),
                'description'         => __( 'Returns SEO data for a specific post.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to retrieve SEO data for.', 'lean-seo' ),
                'category'            => 'site',
                            'required'    => true,
                        ),
                    ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                'category'            => 'site',
                        'canonical'   => array( 'type' => 'string' ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                'category'            => 'site',
                            ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/update-post-seo',
            array(
                'label'               => __( 'Update Post SEO', 'lean-seo' ),
                'description'         => __( 'Updates SEO meta for a specific post.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'update_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to update.', 'lean-seo' ),
                'category'            => 'site',
                            'required'    => true,
                        ),
                        'title'   => array(
                            'type'        => 'string',
                            'description' => __( 'Custom SEO title. Empty string clears the value.', 'lean-seo' ),
                'category'            => 'site',
                        ),
                        'description' => array(
                'category'            => 'site',
                            'type'        => 'string',
                            'description' => __( 'Custom meta description. Empty string clears the value.', 'lean-seo' ),
                'category'            => 'site',
                        ),
                    ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                'category'            => 'site',
                        'canonical'   => array( 'type' => 'string' ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                'category'            => 'site',
                            ),
                        ),
                    ),
                ),
            )
        );
    }

    /**
     * Permission check for sitemap URLs.
     *
     * @return bool
     */
    public static function can_view_sitemaps() {
        return current_user_can( 'manage_options' );
    }

    /**
     * Permission check for post SEO abilities.
     *
     * @param array $input Ability input.
     * @return bool
     */
    public static function can_edit_post( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return false;
        }

        return current_user_can( 'edit_post', $post_id );
    }

    /**
     * Return sitemap URLs.
     *
     * @return array
     */
    public static function get_sitemap_urls() {
        $urls        = array();
        $urls[]      = home_url( '/sitemap.xml' );
        $post_count  = wp_count_posts( 'post' )->publish;
        $pages_needed = (int) ceil( $post_count / 1000 );

        if ( $pages_needed <= 1 ) {
            $urls[] = home_url( '/sitemap-posts.xml' );
        } else {
            for ( $i = 1; $i <= $pages_needed; $i++ ) {
                $urls[] = home_url( sprintf( '/sitemap-posts-%d.xml', $i ) );
            }
        }

        $urls[] = home_url( '/sitemap-pages.xml' );
        $urls[] = home_url( '/sitemap-categories.xml' );
        $urls[] = home_url( '/sitemap-tags.xml' );

        return $urls;
    }

    /**
     * Return SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function get_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'Post ID is required.', 'lean-seo' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'lean_seo_post_not_found', __( 'Post not found.', 'lean-seo' ) );
        }

        $custom_title       = get_post_meta( $post_id, '_lean_seo_title', true );
        $custom_description = get_post_meta( $post_id, '_lean_seo_description', true );
        $title              = $custom_title ? $custom_title : get_the_title( $post );
        $description        = $custom_description ? $custom_description : self::generate_description( $post );

        return array(
            'post_id'     => $post_id,
            'title'       => $title,
            'description' => $description,
                'category'            => 'site',
            'canonical'   => get_permalink( $post ),
            'custom'      => array(
                'title'       => $custom_title ? $custom_title : '',
                'description' => $custom_description ? $custom_description : '',
                'category'            => 'site',
            ),
        );
    }

    /**
     * Update SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function update_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'Post ID is required.', 'lean-seo' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'lean_seo_post_not_found', __( 'Post not found.', 'lean-seo' ) );
        }

        if ( array_key_exists( 'title', $input ) ) {
            $title = sanitize_text_field( $input['title'] );
            if ( '' !== $title ) {
                update_post_meta( $post_id, '_lean_seo_title', $title );
            } else {
                delete_post_meta( $post_id, '_lean_seo_title' );
            }
        }

        if ( array_key_exists( 'description', $input ) ) {
            $description = sanitize_textarea_field( $input['description'] );
            if ( '' !== $description ) {
                update_post_meta( $post_id, '_lean_seo_description', $description );
            } else {
                delete_post_meta( $post_id, '_lean_seo_description' );
            }
        }

        return self::get_post_seo( array( 'post_id' => $post_id ) );
    }

    /**
     * Generate fallback description for a post.
     *
     * @param WP_Post $post Post object.
     * @return string
     */
    private static function generate_description( $post ) {
        if ( $post->post_excerpt ) {
            return wp_strip_all_tags( $post->post_excerpt );
        }

        $content = wp_strip_all_tags( strip_shortcodes( $post->post_content ) );
        return wp_trim_words( $content, 30, '...' );
    }
}
